name: SBT CI

permissions:
  contents: read

on:
  pull_request:
    branches: ["*"]

jobs:
  call-sbt-ci:
    uses: project-ncl/shared-github-actions/.github/workflows/sbt-ci.yml@f0ec1696c5dfea0d6d16c135c14f54049b94edaf # v0.0.24
    with:
      build_args: "clean; compile; +test; makePom; scripted smeg-plugin/*"
      upload_artifacts: true
