name: SBT CI

permissions:
  contents: read

on:
  pull_request:
    branches: ["*"]

jobs:
  call-sbt-ci:
    uses: project-ncl/shared-github-actions/.github/workflows/sbt-ci.yml@a27e6fba6b28bbb96881ec096e9c8ea5a538f481 # main
    with:
      build_args: "clean; compile; +test; makePom; scripted smeg-plugin/*"
      upload_artifacts: true
