name: Build snapshot version and upload

permissions:
  contents: read

on:
  push:
    branches: ["main"]

jobs:
  call-snapshot-job:
    uses: project-ncl/shared-github-actions/.github/workflows/sbt-snapshot.yml@a27e6fba6b28bbb96881ec096e9c8ea5a538f481 # v0.0.22
    with:
      project_name: "project-ncl/smeg"
      build_args: "clean; compile; +test; scripted smeg-plugin/*"
      snapshot_deploy_command: "sbt -v aetherDeploy"
    secrets:
      SNAPSHOT_USER: ${{ secrets.SONATYPE_USERNAME }}
      SNAPSHOT_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
