name: Build snapshot version and upload

permissions:
  contents: read

on:
  push:
    branches: ["main"]

jobs:
  call-snapshot-job:
    uses: project-ncl/shared-github-actions/.github/workflows/sbt-snapshot.yml@646d9b629925d6405fb06ed1476aefd6b2cdca86 # v0.0.23
    with:
      project_name: "project-ncl/smeg"
      build_args: "clean; compile; +test; scripted smeg-plugin/*"
      snapshot_deploy_command: "sbt -v aetherDeploy"
    secrets:
      SNAPSHOT_USER: ${{ secrets.SONATYPE_USERNAME }}
      SNAPSHOT_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
